#%RAML 1.0 NamedExample
value:
  bookingId: b1
  bookingStartDate: 2020-09-10
  bookingEndDate: 2020-09-15
  amenitiesSelected: 
    - wi-fi
    - room-service
  transportSelected: 
    - town car service
    - shuttle service
  food: vegetarian
  room: 
    roomId: rm1 
    roomType: single room
    amount: 40000