#%RAML 1.0 NamedExample
value:
  registrationId: r1
  customerName: Ruchi
  title: Ms
  address: 
    addressLine: H-1,HCL Apartments
    city: Noida
    state: UP
    country: India
    pincode: '201301' 
  paymentType: Cash


          