#%RAML 1.0
title: w3schoolsAPI

/w3schools:
  get:
    queryParameters:
      data:
        enum:
          - customers
          - orders
          - products
          - suppliers
          - shippers
          - order_details
          - employees
          - categories
    responses:
      200:
        body:
          application/json:
            example:
              {
              "CategoryID" : 1,
              "CategoryName" : "Beverages",
              "Description" : "Soft drinks, coffees, teas, beers, and ales"
             }
              
            
  