#%RAML 1.0 DataType
type: object
displayName: Hotel DataType
description: Hotel Details
properties:
  hotelId: string
  hotelName: string
  rating: string
  rooms: 
    type: array
    items: !include Room.raml 
  paymentTypes: string[]
  amenities: string[]
  transport: string[]
  food: string[]
  languagesSpoken: string[]
  address: !include Address.raml
examples:
  example1: !include ../examples/HotelExample1.raml
  example2: !include ../examples/HotelExample2.raml
