#%RAML 1.0 NamedExample
value:
  CustomerID? : 7
  CustomerName : Blondel père et fils
  ContactName : Blondel père et fils
  Address : 24, place Kléber
  City : Strasbourg
  PostalCode : 67000
  Country : France