#%RAML 1.0 NamedExample
value:
  bookingId: b2
  bookingStartDate: 2020-10-20
  bookingEndDate: 2020-10-25
  amenitiesSelected: 
    - wi-fi
    - gym
    - dry cleaning
  transportSelected: 
    - limousine service
    - valet parking
  food: vegetarian
  room: 
    roomId: rm1 
    roomType: single room
    amount: 40000