#%RAML 1.0 NamedExample
value:
  hotelId: h2
  hotelName: Imperial Hotel
  rating: '5 star'
  price: 50000
  address: 
    addressLine: imperial street A
    city: delhi
    state: delhi
    country: India
    pincode: '1100011'
  rooms: 
    - # item1 
        roomId: rm3
        roomType: single room
        amount: 30000
    - # item2 
        roomId: rm4
        roomType: double room
        amount: 50000
  paymentTypes:
     - cash
     - credit card
     - paytm
  amenities: 
    - wifi
    - room-service
  transport: 
    - town car service
    - shuttle service
  food: 
    - veg
    - non-veg
  languagesSpoken: 
   - english
   - hindi