#%RAML 1.0 NamedExample
value:
  hotelId: h1
  hotelName: Taj Hotel
  rating: '5 star'
  address: 
    addressLine: taj street A
    city: noida
    state: Uttar Pradesh
    country: India
    pincode: '201301'
  rooms: 
    - # item1
        roomId: rm1 
        roomType: single room
        amount: 40000
    - # item2
        roomId: rm2
        roomType: double room
        amount: 70000
  paymentTypes:
     - cash
     - credit card
     - paytm
  amenities: 
    - wifi
    - room-service
  transport: 
    - town car service
    - shuttle service
  food: 
    - veg
    - non-veg
  languagesSpoken: 
    - english
    - hindi