#%RAML 1.0 NamedExample
value:
  registrationId: r2
  customerName: Rimpy
  title: Ms
  address: 
    addressLine: H-1,HCL Apartments
    city: DElhi
    state: Delhi
    country: India
    pincode: '110001' 
  paymentType: Credit Card

          